### ISSUE TITLE
Mogućnost registrovanja iako su uneseni isti podaci kao kod već postojećeg korisnika

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#1]
**Komponenta:** Registracija novog korisnika

**Commit ID:** 42bf63ba098e1b979a64cb297331b0cbb7920add

**Opis:**
Moguće se registrovati iako su uneseni isti podaci kao kod već postojećeg korisnika. 

**Koraci za reproduciranje problema:**
1. Pokrenuti backend i frontend
2. Kliknuti na "Register"
3. Unijeti podatke kao na slici ispod (možete staviti bilo koju šifru)
![image](https://cloud.githubusercontent.com/assets/17412265/26762006/3c45209c-493a-11e7-80b6-87aa7da8e8a4.png)
4. Kliknuti na "Register"
5. Kliknuti na "Nazad na početnu"
6. Ponoviti korake 2-4

**Dobijeni rezultati:**
Ispis poruke o uspješnoj registraciji.
![image](https://cloud.githubusercontent.com/assets/17412265/26762017/b532854e-493a-11e7-96c4-e4a72f46c6f5.png)

**Očekivani rezultati:**
Poruka o postojanju korisnika sa istim podacima.

**Comment by goldlil** [comment]
Ispravljeno u novoj verziji!
