### ISSUE TITLE
Neslaganje sa NFZ2

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#10]
**Komponenta:** Naslovna strana, početna strana nakon prijave predavača/studenta
**Commit ID:** 42bf63ba098e1b979a64cb297331b0cbb7920add
**Opis:** 
Sistem se ne slaže sa NFZ2 koji glasi: 
![image](https://cloud.githubusercontent.com/assets/17412265/26762853/426ffd8e-4949-11e7-8319-61fac4bcd026.png)
Neslaganje se odnosi na to da sve labele u GUI-u nisu na bosanskom jeziku (login, register i slično).

**Comment by Spaho1** [comment]
Mislim da se NFZ - ne broje u bagove... Provjerit ćemo...

**Comment by Delaylah** [comment]
Implementirano  , razrjesen.
