### ISSUE TITLE
Neslaganje sa NFZ4

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#11]
**Komponenta:** Sve podstranice fronta
**Commit ID:** 42bf63ba098e1b979a64cb297331b0cbb7920add
**Opis:** 
Sistem se ne slaže sa NFZ4 koji glasi: 
![image](https://cloud.githubusercontent.com/assets/17412265/26762876/e211c458-4949-11e7-9be3-8bfa24190b99.png)
Neslaganje se odnosi na odsustvo opcije za pomoć na svim prozorima.

**Comment by Delaylah** [comment]
Implementirano. Razrjeseno.
