### ISSUE TITLE
User profile i settings tabovi ne otvaraju nista

### ISSUE THREAD

**Issue by ssorguc** [SoftverInzenjeringETFSA/SI2016_TIM12#14]
Komponenta: Student forme
Commit ID: 21758e2

Opis:
Kada se otvore opcije Settings i User profile ne postoje nikakave akcije, tj. nije implementirano.

Koraci za reproduciranje problema:
Pokrenuti forntend i backend (pokrenuti aplikaciju)
Logovati se kao student
Otvoriti tab i kliknuti na Settings i User profile
![image](https://cloud.githubusercontent.com/assets/17412267/26763366/25425758-4952-11e7-92df-e14a157efe2a.png)

**Comment by Delaylah** [comment]
Implementirano, razrjesen.
