### ISSUE TITLE
Mogućnost dodavanja više potpuno istih predavača/administratora

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#16]
**Komponenta:** Komponente vezane za dodavanje predavača

**Commit id:** 58eb43e  
                        a63572e
                        a63572e

**Opis:**
Moguće je dodati više potpuno istih predavača pri čemu dolazi do sukoba pri login-u sa registrovanim računom vezanim za predavača/administratora

**Koraci za reprodukciju:**
-Prijaviti se kao administrator
-Odabrati opciju za dodavanje predavača ili administratora
-Unijeti podatke nekog od već postojećih predavača/administratora

**Slike:**
-slike prikazuju više, potpuno istih predavača/administratora
![capture](https://cloud.githubusercontent.com/assets/17412248/26764907/e9b957e4-4970-11e7-894c-0d6c4a650f30.PNG)
![capture](https://cloud.githubusercontent.com/assets/17412248/26764924/44aceeae-4971-11e7-9184-087298356e8c.PNG)

**Comment by osokolovic1** [comment]
Dodatno:
moguće je dodati i više istih korisnika - studenata kao i više itih kurseva.

**Comment by Delaylah** [comment]
Pod istim imenom i prezimenom da.. Jer mogu postojati dvije Ajle Sukrije, ajmo reci , ali ako se doda razlicit jmbg onda su svrstani kao razliciti korisnici.. Ovo jos jednom provjeriti.. Jel jmbg..

**Comment by goldlil** [comment]
Ispravljeno u novoj verziji!
