### ISSUE TITLE
Mogućnost registracije sa podacima admina

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#18]
**Komponente:** Komponente vezane za registraciju korisnika sistema(kontroleri, servisi i repozitoriji vezani za pocetnu stranu, predavača, administratora i studenta)

**Commit id:** a63572e04dbcedb49cce80b82c40f79e5c08eba7

**Opis:** 
Bilo koji korisnik ima mogućnost da se registruje sa podacima administratora nakon čega odgovarajući administrator gubi privilegije. Kada se administrator čiji su podaci iskorišteni pri registraciji korisnika prijavi u sistem sa svojim podacima, bit će prijavljen kao obični korisnik-student.

**Koraci za reprodukciju:**
-Registrovati novog administratora
-Odjaviti se
-Pristupiti formi za registraciju vezanoj za korisnike
-Unijeti iste podatke kao i administrator
-Pokušaj prijave sa podacima daje rezultat koji je prikazan na prvoj slici u dijelu za slike

**Slike:**
![capture](https://cloud.githubusercontent.com/assets/17412248/26765039/99f3ccd2-4973-11e7-92af-10df9d973831.PNG)

**Comment by goldlil** [comment]
Ispravljeno u novoj verziji!
