### ISSUE TITLE
Registracija studenta kao predavača

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#19]
**Komponente:** Registracija novog korisnika

**Commit ID:** 42bf63b

**Opis:** 
Korisnik se na početku može registrovati sa podacima nekog od predavača. Nakon toga, korisnik-student ulazi na stranicu kao predavač.

**Koraci za reprodukciju:**
-Prijaviti se kao administrator i izvršiti registraciju novog predavača
-Odjaviti se
-Pristupiti početnoj formi za registraciju i registrovati novog korisnika sa prethodno unesenim podacima za predavača
-Upravo registrovani korisnik-student ima privilegije predavača

**Slike:**
-predavač:
![capture](https://cloud.githubusercontent.com/assets/17412248/26765145/1501297c-4976-11e7-9e6b-3bb46f11538e.PNG)

-registracija studenta sa istim podacima
![capture](https://cloud.githubusercontent.com/assets/17412248/26765148/4667e320-4976-11e7-8c6a-e632588bc358.PNG)

-upravo registrovani student pristupa stranici vezanoj za predavače
![capture](https://cloud.githubusercontent.com/assets/17412248/26765153/6b990d68-4976-11e7-800c-c1c092ac9bd8.PNG)

**Comment by goldlil** [comment]
Ispravljeno u novoj verziji!
