### ISSUE TITLE
Nejasna poruka o nevalidnosti podataka 

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#2]
**Komponenta:** Registracija novog korisnika

**Commit ID:** 42bf63ba098e1b979a64cb297331b0cbb7920add

**Opis:**
Poruka o nevalidnosti podataka ne specificira koji uneseni podaci nisu validni, osim u slučaju razlike između unesenih šifri.

**Koraci za reproduciranje problema:**
1. Pokrenuti backend i frontend
2. Kliknuti na "Register"
3. Unijeti nevalidne podatke, npr.:
![image](https://cloud.githubusercontent.com/assets/17412265/26762098/53c2bd68-493c-11e7-98c1-2c0f329a6533.png)
4. Kliknuti na "Register"

**Dobijeni rezultat:** 
Poruka kao na slici: 
![image](https://cloud.githubusercontent.com/assets/17412265/26762105/710c0014-493c-11e7-8fad-dbd428a3b2f1.png)

**Očekivani rezultat:**
Poruka koja sadrži podatke o tome koji uneseni podaci nisu validni.

**Comment by Delaylah** [comment]
U SRS* ne kaze KOJI podaci nisu validni, nego ispisuje poruka da podaci nisu validni. Ovo nije Bug
