### ISSUE TITLE
JMBG je pogrešno validiran u svakoj formi

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#20]
**Komponente:** Registracija korisnika, Registracija administratora, Registracija predavača

**Commit ID:** 42bf63b

**Opis:**
JMBG nije pravilno validiran prema datumu rođenja. Jedino što je validirano je to da mora imati 13 brojeva.

**Koraci za reprodukciju:**
-Pristupiti formi za registraciju administratora, predavača ili početnoj formi za registraciju
-Unijeti primjer: 1111111111111
-Korisnik je registrovan sa nevalidnim JMBG

**Comment by Delaylah** [comment]
Ne pise u SRS* Pravilno validiran JMBG po Bosanskim pravilima
