### ISSUE TITLE
Korisnik prikazan i nakon brisanja, Reload vraća na početnu formu

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#21]
**Komponente:** Prikaz svih administratora, studenata, predavač, kurseva

**Commit ID:** a63572e

**Opis:** prikazani korisnik(administrato - u dijelu svi Administratori, Predavač - u dijelu Svi predavači, Student u dijelu Svi studenti) je nakon brisanja i dalje prikazan u tabeli sve dok se ne uradi refresh stranice. Nakon refresh-a dešava se da je korisnik prebačen na početnu formu i mora ponovo prolaziti proces prijave u sistem.

**Koraci za reprodukciju:**
-Pristupiti dnekom od dijelova: Svi administratori, Svi studenti, Svi predavači ili Svi kursevi
-Izbrisati nešto od navedenog
-Vidimo da je izbrisani sadržaj i dalje prisutan
![capture](https://cloud.githubusercontent.com/assets/17412248/26765247/2b4b820c-4978-11e7-82af-f5c89166ad5b.PNG)

-Nakon refresh-a stranice, prikazana je početna forma
![capture1](https://cloud.githubusercontent.com/assets/17412248/26765248/2fd8cb18-4978-11e7-9703-3d172365234d.PNG)

**Comment by goldlil** [comment]
Stranica je web aplikacija, i kao ista radi bez reloada. Nakon što se stranica reloada tražit će se opet unos login podataka.  Nakon što opet uđete u stranicu vidjet ćete da zadati prevac ne postoji. Kada se otvori bilo koji tab i vrati se na tab predavaca obrisanog predavaca nema.

**Comment by osokolovic1** [comment]
Nakon klika na button moguće je izvršiti reload stranice tako da to korisnik ne mora raditi, i pri tome se vratiti na istu stranicu. Mislim da nije u redu da korisnik mora ponovo prolaziti kroz login nakon svakog reloada stranice?

**Comment by goldlil** [comment]
Kada se korisnik obriše, to se neće odmah odraziti na tabelu korisnika. Ako odete na neku drugi tab aplikacije i vratite se na onaj na kojem ste obrisali onda je vidljivo da je korisnik obrisan. Sesija nakon reloada nije implementirana. Aplikacija može raditi bez reloada, nakon reloada korisnik više nije prijavljen. Ova greška bi trebala da sadržio samo dio oko sesije da bi se ikakva labela na nju mogla primjeniti.
