### ISSUE TITLE
Nije omogućeno uređivanje profila

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#22]
**Komponente:** Uređivanje korisničkih podataka

**Commit ID:**/

**Opis:** Funkcionalni zahtjev FZ 13 Uređivanje korisničkih podataka nije implementiran

**Koraci za reprodukciju:**
-Prijaviti se kao administrator/predavač/student
-Nije omogućeno uređivanje profila

**Comment by ssorguc** [comment]
emina je ovim jednim issue-om napisala sta nije implementirano 
![image](https://cloud.githubusercontent.com/assets/17412267/26765293/67bb1ad0-4979-11e7-8109-343ac8655cbf.png)
