### ISSUE TITLE
Labela datum rođenja

### ISSUE THREAD

**Issue by ssorguc** [SoftverInzenjeringETFSA/SI2016_TIM12#23]
**Komponenta**: Registracijska forma
**Commit ID:**  c60a738
**Opis:** Nije neki veliki issue (više je vezan za dizajn), ali trebala bi da postoji labela ili neka oznaka kod date-time pickera kako bi se znalo da se radi o datumu rođenja.
![image](https://cloud.githubusercontent.com/assets/17412267/26765257/7fa3ab9a-4978-11e7-83c5-e39f93728603.png)
**Koraci za reprodukciju:**
Pokretanje aplikacije
Otvaranje registracijske forme

**Comment by Delaylah** [comment]
Implementirano. Razrjesneno.
