### ISSUE TITLE
Šifra admina prikazana u tabeli pod poljem prezime

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#24]
**Komponente:** Svi administratori

**Commit ID:**  42bf63b 

**Opis:**
Prijavljeni administrator može vidjeti šifre svih ostalih administratora jer je šifra prikazana u polju Prezime u tabeli Svi administratori

**Koraci za reprodukciju:**
-Prijaviti se kao administrator
-Pristupiti dijelu Svi administratori

**Slike:**
-šifra prikazana u polju za prezime
![capture](https://cloud.githubusercontent.com/assets/17412248/26765315/d9124f32-4979-11e7-8f58-be1a60316a2f.PNG)

**Comment by Delaylah** [comment]
Ne , nego je stavka prezimena koja je unesena u bazu je izgleda  "Password".

**Comment by osokolovic1** [comment]
![capture](https://user-images.githubusercontent.com/17412248/26896513-51238cdc-4bc5-11e7-8a05-1d7e6979af53.PNG)

**Comment by Delaylah** [comment]
Hvala kolegi na dodatnom pojasnjenju. Implementirano, razrjeseno.
