### ISSUE TITLE
Brisanje administratora nije implementirano

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#25]
**Komponente:** Brisanje administratora

**Commit ID:** /

**Opis:**
Administratora je moguće dodati, nakon čega nije moguće brisanje administratora.

**Koraci za reprodukciju:**
-Prijaviti se kao administrator
-Pristupiti dijelu Svi administratori
-Pokušati izbrisati administratora klikom na dugme Izbriši
-Rezultat:
![capture](https://cloud.githubusercontent.com/assets/17412248/26765371/1637811a-497b-11e7-98f9-fc6c286c81d9.PNG)

**Comment by Delaylah** [comment]
Ovo nije Bug s obzirom da smo napisali da ce se implementirati u daljem radu.. Kao sto je predmetni asistent rekao da imenujemo.

**Comment by goldlil** [comment]
Dodano u novoj verziji.
