### ISSUE TITLE
Korisnik mora biti registrovan da bi vidio materijale

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#27]
**Komponentne:** Prikaz materijala

**Commit ID:** a63572e  42bf63b  

**Opis:**
-Ovo nije usaglašeno sa SRS-om. Potrebno je omogućiti korisniku - studentu da vidi neke materijale koji će ga približiti gradivu kursa i navesti na upis. Ovdje, korinik - student mora biti registrovan da bi vidio materijale

**Koraci za reprodukciju:**
/

**Slike:**
/

**Comment by Delaylah** [comment]
Sa klijentom smo se slozili da korisnik mora biti ulogovan da bi vidio sve materijale koje moze skinuti, jer samo registrovani korisnik moze pristupiti materijalima..

**Comment by Delaylah** [comment]
![image](https://user-images.githubusercontent.com/11279063/26904591-eb914c7e-4be2-11e7-8247-9712ee82361f.png)
