### ISSUE TITLE
Nakon dodavanja lekcije vraća na ponovno logiranje

### ISSUE THREAD

**Issue by ssorguc** [SoftverInzenjeringETFSA/SI2016_TIM12#28]
**Komponenta:** Forma predavača
**Commit ID:** c60a738
Opis:
Nakon sto se uploaduje fajl i klikne na dodaj lekciju vrati se na formu naslovnu formu, te se ponovo mora vrsiti log in.
![image](https://cloud.githubusercontent.com/assets/17412267/26765415/f2f83202-497b-11e7-8515-9b4be9201b1e.png)
Koraci za reprodukciju:
Pokrenuti aplikaciju
Logovati se kao predavač
Otvoriti opciju za dodavanje lekcije
Ispuniti potrebna polja 
Kliknuti na "Dodaj lekciju"

Ocekivani rezultat:
Trebalo bi da se otvori forma courseware gdje je dodata.

**Comment by Delaylah** [comment]
**novi SRS indicira da je lekcija dodana sa alertom bez preusmjeravanja, i to Kada se lekcija doda ona je izlistana u tabeli lekcija .. nigdje vise.Ova funkcionalnost svakako nije implementirana tj povzana sa bazom**
--Funkcionlanost za povezati
