### ISSUE TITLE
Početna stranica ne postoji

### ISSUE THREAD

**Issue by osokolovic1** [SoftverInzenjeringETFSA/SI2016_TIM12#29]
**Komponentne:** Početna stranica

**Commit ID:** a63572e  42bf63b  

**Opis:**
-Ovaj dio nije usaglašen sa SRS-om. U SRS dokumentu je naglašeno da administrator mora imati mogućnost dodavanja novosti na početnu stranicu škole. Dakle razlikuje se courseware(kojem mogu pristupiti samo registrovani korisnici) i početna stranica(kojoj mogu pristupiti svi koji pregledaju stranicu škole) - Pogledati FZ 18(3.2.18). U slučaju postojeće implementacije, početna stranica prikazuje formu za odabir opcije za prijavljivanje ili registrovanje.

**Koraci za reprodukciju:**
-Pristupiti početnoj stranici

**Slike:**
-trenutni izgled početne stranice
![capture](https://cloud.githubusercontent.com/assets/17412248/26765497/647cfda8-497d-11e7-92e0-98152bf91b03.PNG)

**Comment by Delaylah** [comment]
**Pocetna stranica i naslovna stranica nisu definisane precizno, naslovna stranica je Ona koja sadrzi login i registraciju, time da pocetna stranica je na eng."Dashboard page" koju svaki registrovani korisnik vidi. Ovo je stavka prmjenjenog SRS. Nema potrebe za implementacijom sadrzaja na Naslovnoj stranici. 
--- JOS JEDNOM VIDJETI NOVI SRS.

**Comment by Delaylah** [comment]
Bug nije prepoznat pod Bug-ovima SRSa, razrjesen.
