### ISSUE TITLE
Neimplementirane funkcionalnosti 

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#3]
**Komponenta:** /

**Commit ID:** /

**Opis:**
Nisu implementirane sljedeće funkcionalnosti: 
- Oduzimanje prava pristupa studentu
- Online predavanje uz live prenos i chat
- Slanje urađenog testa
- Unos i objavljivanje rezultata testiranja
- Uređivanje korisničkih podataka
- Otključavanje određenog nivoa kursa

**Comment by osokolovic1** [comment]
Pored ovoga:
- Pregled testova, termina i lekcija
- Obrada zahtjeva za pristup kursevima(administrator)

**Comment by osokolovic1** [comment]
-Organizacija grupa studenata
