### ISSUE TITLE
Nejasnoće u nazivima labela i tabova kod formi predavača

### ISSUE THREAD

**Issue by ssorguc** [SoftverInzenjeringETFSA/SI2016_TIM12#30]
**Komponenta:** Forme predavača
**Commit ID:** c60a738
**Opis:** Generalno ima nedostatka vezanih za labele, nazive dugmica na formama predavača. Kada se klikne na tab dodaj termin predavanja kursa (naziv tab-a treba biti jasan npr. Dodaj termin predavanja), zatim na formi koja se otvori dugmić se zove "Register", što bi trebalo promjeniti u Dodaj termin ili nesto slično. Zatim, labela "Dodaj učitelja" kada se otvori tab Dodaj test za kurs (ime ovog taba treba promjenit u nesto jasnije i konciznije npr. Dodaj test) je tu zalutala greškom - potrebno promjeniti tekst labele.
![image](https://cloud.githubusercontent.com/assets/17412267/26765448/6e89ee6a-497c-11e7-9b94-10c3ae867e6c.png)
![image](https://cloud.githubusercontent.com/assets/17412267/26765560/6c187b22-497e-11e7-8edb-71414b680201.png)

**Koraci za reprodukciju:**
Pokretanje aplikacije
Logiranje kao predavač
Otvaranje taba Dodaj termin predavanja kursa
Otvaranje taba Dodaj test za kurs

**Comment by Delaylah** [comment]
Implementirano, razrjeseno.
