### ISSUE TITLE
Lekcije se ne spremaju u bazu podataka

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#4]
**Komponenta:** Dodaj novu lekciju

**Commit ID:** 42bf63ba098e1b979a64cb297331b0cbb7920add 

**Opis:**
Nakon dodavanja lekcije, lekcija se ne sprema u bazu podataka.

**Koraci za reproduciranje problema:** 
1. Pokrenuti backend i frontend
2. Kliknuti na "Login"
3. Unijeti podatke već postojećeg predavača: 
username: adam
password: adaasdm
4. Kliknuti na "Dodaj novu lekciju za kurs"
5. Unijeti naziv lekcije i uploadovati lekciju
7. Kliknuti na "Dodaj lekciju"

**Dobijeni rezultat:** 
Nepostojanje lekcije u bazi podataka
**Očekivani rezultat:**
Lekcija se nalazi u bazi podataka

**Comment by dsabanovic1** [comment]
u PredavacController dodana metoda dodajLekciju.
