### ISSUE TITLE
Lekcija ne postoji u backendu

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#5]
**Komponenta:** Dodavanje nove lekcije

**Commit ID: ** 42bf63ba098e1b979a64cb297331b0cbb7920add

**Opis:**
Ne postoje klase potrebne za dodavanje nove lekcije u backendu, nego samo forma u frontendu.

**Comment by dsabanovic1** [comment]
Napravljen model Lekcija, te odgovarajuća tabela u bazi.
