### ISSUE TITLE
Dodavanje testa nije u skladu sa SRS-om

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#6]
**Komponenta:** Dodaj novu lekciju

**Commit ID:** 42bf63ba098e1b979a64cb297331b0cbb7920add

**Opis:** 
Forma za dodavanje testa kao i popratne klase nisu u skladu sa SRS-om (pogledati funkcionalni zahtjev "Dodavanje lekcija od strane predavača").

**Comment by Delaylah** [comment]
Novi SRS* ali nije implementirano
