### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#8]
**Komponenta:** više komponenti

**Commit ID: ** 42bf63ba098e1b979a64cb297331b0cbb7920add

**Opis:** 
Neke forme imaju zbunjujući ui. 
Forma za dodavanje nove lekcije: 
![image](https://cloud.githubusercontent.com/assets/17412265/26762484/638d29ca-4943-11e7-987c-054ec6d830b5.png)
Forma za dodavanje novog testa:
![image](https://cloud.githubusercontent.com/assets/17412265/26762486/6988b178-4943-11e7-8562-fce31bc12c9c.png)

**Koraci za reproduciranje problema:**
1. Pokrenuti backend i frontend
2. Kliknuti na "Login"
3. Unijeti podatke već postojećeg predavača:
username: adam
password: adaasdm
4. Kliknuti na "Dodaj novu lekciju za kurs" ili "Dodaj test za kurs"

**Comment by Delaylah** [comment]
Implementirano, Razrjeseno.
