### ISSUE TITLE
Connection string, username i password za pristup bazi nisu prema uputama sa c2

### ISSUE THREAD

**Issue by hosemina** [SoftverInzenjeringETFSA/SI2016_TIM12#9]
**Komponenta:** application.properties
**Commit ID:** a63572e04dbcedb49cce80b82c40f79e5c08eba7
**Opis:** 
Podaci za pristup bazi podataka navedeni u application.properties nisu prema uputama sa c2 što uzrokuje error i nemogućnost pokretanja projekta. 
**Koraci za reproduciranje problema:**
1. Otvoriti backand projekat u Eclipse
2. Pokrenuti aplikaciju kao Spring Boot aplikaciju
- Greška: 
![image](https://cloud.githubusercontent.com/assets/17412265/26762730/6e5c0c00-4947-11e7-8a3a-14ea9824e583.png)

**Comment by goldlil** [comment]
Ispravljeno u novoj verziji!
